[project]
name = "2-micro-job-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JasmineChhotaray", email = "chhotaray.jasmine@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-groq>=1.1.3",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
2-micro-job-agent = "2_micro_job_agent:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
